### ISSUE TITLE
Review docker instructions in public documentation

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma.com#100]
From https://github.com/metanorma/metanorma-csd/pull/84

flavor-sample-default-build-instructions.adoc is worded as:

````
[source,console]
--
docker run \
    -v "$(pwd)":/metanorma/ \
    -w /metanorma ribose/metanorma \
    "metanorma {{ include.flavor.build.cli_flags }} {{ include.sample_filename }}"
--
````

@abunashir indicates that the quotes on the final line should be removed. Abu, please confirm, and issue a PR if so. Please review any other mentions of docker in this repository as well, since this is the public facing documentation.

**Comment by ronaldtse** [comment]
@opoudjis I confirm we need to remove the double quotes in the final line.
