### ISSUE TITLE
Add an entry for ISO Word styling on NOTEs and EXAMPLEs

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#108]
Add explanation for correct formatting of ISO documents in Word for NOTEs and EXAMPLEs.

From ISO Editor:

> When documents are processed at ISO, NOTEs and EXAMPLEs are so styled that they would appear in a font one-size smaller than the normal body text. Other than that, there’s no hard rule on how the EXAMPLEs/NOTEs are formatted.
>
> If an EXAMPLE/NOTE contains multiple paragraphs, the usual practice is to follow the indentation in the submissions. It is possible to put the content in borderless tables, or other formats, to get the indentation right. But if there’s no special indentation in the submitted text, there would be no indentation in the rendered PDF.
>
> For the EXAMPLEs in DP2, I suppose the special format (“EXAMPLE 2” on its own line; the frame around the text) was used for ease of understanding; after all, “EXAMPLE 2” provides examples for EXAMPLEs in documents, it could cause confusion if they all use the same format (it’s already quite convoluted putting them in this sentence).

**Comment by ronaldtse** [comment]
Better yet this could be a blog post with screenshots on how NOTEs and EXAMPLEs can be encoded (i.e. source code + rendered look). Will be very useful for authors.

**Comment by opoudjis** [comment]
I am going to make it very clear, once again, that there is no way I am going to rewrite the documentation of Metanorma for a FOURTH time: I will never do this, and if you want this done, you hire someone else. It also goes without saying that this will make metanorma documentation more unnavigable, not less.

I actually see nothing to document here at all for metanorma.com. We don't document rendering, we never have, and there is no reason to. And the lack of navigability of metanorma.com will not be addressed with more random content.

Therefore I will not generalise this task past a desultory blog post. There will be no cartoons.

**Comment by ronaldtse** [comment]
This task is to document our decisions for the user. This does not seem to require extra work.

**Comment by ronaldtse** [comment]
Which part of this makes this sound like a “rewrite”?
