### ISSUE TITLE
Apply text background highlight on <em>?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#11]
How about something like this for highlighting? This is probably for the open project theme.

![screen shot 2018-08-28 at 10 16 38 am](https://user-images.githubusercontent.com/11865/44696815-a342e580-aaab-11e8-8688-8d58d046cd64.png)

**Comment by strogonoff** [comment]
@ronaldtse I believe the best practice is to pick one trait with which to differentiate accented text from surroundings. Meaning I’d stick with either color or font style (or size, or weight), but not both at the same time. If we disagree here perhaps we should defer to @riksalazar’s opinion as the designated designer.

**Comment by ronaldtse** [comment]
I agree. Can you help settle this with your designer eye? Thanks!

CC: @ribose-jeffreylau

**Comment by ronaldtse** [comment]
It's been a while, and probably no longer relevant. Closing it.
