### ISSUE TITLE
Add documentation on ISO stage attribute that some stages are handled by ISO/CS, not the author

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#116]
We should also give some more information for MN ISO on stages that are handled by ISO/CS, not the authors.

The last stage the author will handle is DIS (or DTR, DTS, DAM depending on doctype).

The F-stages, like FDIS and FDAM, and subsequent ones (like PRF, Pub) are created by ISO/CS.

Functionality wise, we want to retain the ability to use those codes (e.g. for mirroring and tracking purposes), but just let the authors know in a normal submission process, those codes are not used.

**Comment by opoudjis** [comment]
Since I don't know the inner workings of ISO, and you do: is that list exhaustive?
