### ISSUE TITLE
Document how to use Formula vs Inequality

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#128]
> Because the output is multilingual, we will need the labels Equation and Inequality introduced into the YAML. So we won't have an open-ended set of labels: we will have Equation as the default (under "formula"), and allow an option attribute %inequality:

The implemented solution seems proper -- @opoudjis could you help document this? It "might" be the case that it is more generic than ITU.

---
Because the output is multilingual, we will need the labels Equation and Inequality introduced into the YAML. So we won't have an open-ended set of labels: we will have Equation as the default (under "formula"), and allow an option attribute %inequality:

```adoc
[stem%inequality]
++++
A
++++
```

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-itu/issues/24#issuecomment-532246692_

**Comment by opoudjis** [comment]
I've already documented it in metanorma.com, have not pushed yet, given all the other changes underway.

````
=== Formulae

By default, formulae are labelled "Equation". Inequalities are indicated through the
option attribute `%inequality`:

[source,asciidoc]
--
[stem%inequality]
++++
A < B
++++
--
````

I'll leave it ITU-specific for now, but it is easy to move up to metanorma-standoc if it is needed elsewhere.

**Comment by ronaldtse** [comment]
@opoudjis can you only close the ticket when it's pushed? It's easy enough to tag the commit with this issue number...

And we'll want to generalize it too.

**Comment by opoudjis** [comment]
I'm generalising, and introducing a differentiation between equations and inequalities; they won't render any different by default, since formula and inequality will have the same YAML label.
