### ISSUE TITLE
AsciiMath page: how to represent "text" in equations

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#137]
> if the user writes (by accident) an additional quotation mark in math mode, like this: stem:["some text""] (notice the additional quotation mark at right) the compiler doesn't generate a new output (and doesn't tell you what went wrong). 

> It happenned to me, and it took me a while to discover where the error was. So, I thought it could be helpful to spread the info.

We should explain the AsciiMath syntax on metanorma.com, especially since it somewhat differs from asciimath.org in implementation.

_Originally posted by @manuel489 in https://github.com/metanorma/metanorma-standoc/issues/128#issuecomment-537735750_

**Comment by opoudjis** [comment]
... in fact, this is documenting the Asciidoctor/Asciimath gem, which is not our job, it's Asciidoctor/Asciimath's.

Failing that, perhaps someone *other than me* can peruse the Asciidoctor/Asciimath source code, and write this up.

**Comment by opoudjis** [comment]
So, this task is to add a page to metanorma.com, documenting the differences between AsciiMath as documented on http://asciimath.org, and AsciiMath as implemented in https://github.com/asciidoctor/asciimath, which is what we use. It will involve going through the code, and listing the AsciiMath commands that are not included in asciimath.org, such as the font commands like _ii_. 

It also should document common gotchas. (A longstanding gotcha: the asciidoctor/asciimath parser is more insistent than the asciimath.org parser about needing to include parentheses in expressions to group parts of it: I found that very early on with fractions.)

This is a page that will be included under author/topics/document-format.

**Comment by strogonoff** [comment]
Just to chime in for a bit—yeah, if it’s in reference-like format then it should be under [author/ref.](https://github.com/metanorma/metanorma.com/blob/master/author/ref/) I’d recommend using existing references ([document attributes](https://raw.githubusercontent.com/metanorma/metanorma.com/master/author/ref/document-attributes.adoc) namely) as a framework for how to structure the new page.

**Comment by tgolubev** [comment]
Hi All! Here is my attempt to document the differences:

## Differences between asciimath.org and https://github.com/asciidoctor/asciimath/blob/master/lib/asciimath/parser.rb:

## Operation Symbols:

parser.rb:

* '\\\\' => {:value => '\\', :type => :operator}  

asciimath.org:

* '\\'   TeX alt: backslash setminus    See: \

--------------------------------------------------------------------------------
## Miscellaneous symbols:

Missing from asciimath.org:
* 'dx' => {:value => 'dx', :type => :identifier},
* 'dy' => {:value => 'dy', :type => :identifier},
* 'dz' => {:value => 'dz', :type => :identifier},
* 'dt' => {:value => 'dt', :type => :identifier},
* '...' => {:value => '...', :type => :operator},
* '\\ ' => {:value => "\u00A0", :type => :operator},
* 'qquad' => {:value => '\u00A0\u00A0\u00A0\u00A0', :type => :operator},
* 'lim' => {:value => 'lim', :type => :operator, :underover => true},
* 'Lim' => {:value => 'Lim', :type => :operator, :underover => true},

--------------------------------------------------------------------------------
## Relation symbols

Missing from asciimath.org:

* ':=' => {:value => ':=', :type => :operator},

-----------------------------------------------------------------------------------

## Logical symbols

All are the same.

-----------------------------------------------------------------------------------

## Grouping brackets

Present in asciimath.org but not in parser.rb:

* abs(x)		|x|
* floor(x)		⌊x⌋
* ceil(x)		⌈x⌉
* norm(vecx)	 ||\vec{x}|| 

-----------------------------------------------------------------------------------

## Arrows

All the same


-----------------------------------------------------------------------------------

## Accents

Missing from parser.rb:

* overset(x)(=)
* underset(x)(=)
* color(red)(x)
* cancel(x)


-----------------------------------------------------------------------------------
## Greek letters

Lots of capital greek letters missing from asciimath.org:

* 'Alpha' => {:value => "\u0391", :type => :identifier},
* 'Beta' => {:value => "\u0392", :type => :identifier},
* 'Epsilon' => {:value => "\u0395", :type => :identifier},
* 'Zeta' => {:value => "\u0396", :type => :identifier},
* 'Eta' => {:value => "\u0397", :type => :identifier},
* 'Iota' => {:value => "\u0399", :type => :identifier},
* 'Kappa' => {:value => "\u039a", :type => :identifier},
* 'Mu' => {:value => "\u039c", :type => :identifier},
* 'Nu' => {:value => "\u039d", :type => :identifier},
* 'Rho' => {:value => "\u03a1", :type => :identifier},
* 'Tau' => {:value => "\u03a4", :type => :identifier},
* 'Upsilon' => {:value => "\u03a5", :type => :identifier},
* 'Chi' => {:value => '\u0393a7', :type => :identifier}, 

-----------------------------------------------------------------------------------

## Standard functions

All the same
 
-----------------------------------------------------------------------------------

## Font commands

Missing from asciimath.org

* 'ii' => {:value => :italic, :type => :font},
* 'bii' => {:value => :bold_italic, :type => :font},
* 'bcc' => {:value => :bold_script, :type => :font},
* 'bfr' => {:value => :bold_fraktur, :type => :font},
* 'bsf' => {:value => :bold_sans_serif, :type => :font},
* 'sfi' => {:value => :sans_serif_italic, :type => :font},
* 'sfbi' => {:value => :sans_serif_bold_italic, :type => :font},

**Comment by opoudjis** [comment]
OK, thank you for this.

I need this comparison turned into an Asciidoc page to be added to metanorma.com; please work with @strogonoff to do so:

> So, this task is to add a page to metanorma.com, documenting the differences between AsciiMath as documented on http://asciimath.org, and AsciiMath as implemented in https://github.com/asciidoctor/asciimath, which is what we use.

* Our format is Asciidoctor. Copy one of the existing pages.
* We need you to list the commands, and what they mean; definition lists are fine, but they need to be text, not source code. For example: `bsf:: bold sans serif font`.
* List separately the additions to asciimath.org in the asciidoctor parser, and the subtractions.

**Comment by opoudjis** [comment]
@tgolubev I am concerned that I have not heard back from you on this task in the past week. I have created a page for you to populate with the required information, in branch feature/asciimath : https://github.com/metanorma/metanorma.com/blob/feature/asciimath/author/ref/asciimath.adoc . Please populate it as requested with specifics of the differences between asciimath.org and Asciidoctor Asciimath.

**Comment by tgolubev** [comment]
@opoudjis I have copied over the differences to asciimath.adoc, but I am not sure about the desired formatting since I am not familiar with Asciidoc formatting. I apologize, but it seems that it would be more efficient if someone skilled with Asciidoc does the final formatting. (My skills with math editing are in LaTeX.)

**Comment by opoudjis** [comment]
Ok, thank you, I'll take it from there.
