### ISSUE TITLE
Markup of draft of the ITU flavor

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#165]
Right now there is no way of marking a DRAFT for ITU.

https://www.metanorma.com/author/itu/authoring/

`:docstage:` only allows published states.

<img width="481" alt="Screen Shot 2019-10-16 at 12 39 03 AM" src="https://user-images.githubusercontent.com/11865/66875080-5b339a80-efad-11e9-9561-088660a1a6c5.png">

Recommendation status does not indicate which stages these are:

<img width="728" alt="Screen Shot 2019-10-16 at 12 39 23 AM" src="https://user-images.githubusercontent.com/11865/66875103-6981b680-efad-11e9-9efd-1228ae2d67aa.png">

**Comment by opoudjis** [comment]
I cannot action this, I don't understand it. The statuses I encoded are what you told me. If there are other statuses, I need to see a list of them.

**Comment by opoudjis** [comment]
And why on earth is this a metanorma.com ticket and not a metanorma-itu ticket?!

**Comment by ronaldtse** [comment]
> And why on earth is this a metanorma.com ticket and not a metanorma-itu ticket?!

Because if there is a way of doing so, we should express it in metanorma.com

**Comment by ronaldtse** [comment]
And the `:draft:` attribute does mark the document as a draft. Let me clarify with ITU.

**Comment by opoudjis** [comment]
Please don't confuse me, Ronald. Assume that all implementation tasks I do will be documented where appropriate. Draft is meaningless without overt draft statuses, and instruction on how draft status is to be displayed on output. 

Despite how convenient it might be for this project, I am still not a mindreader. :-)

**Comment by ronaldtse** [comment]
ITU: there is only one kind of draft until it is “consented” or “determined”. 

I’ve provided the description on metanorma.com about ITU.

**Comment by ronaldtse** [comment]
For the AAP process, maybe we should expand the abbreviations. ITU folks got confused on what they meant, even though they were from their system.

**Comment by opoudjis** [comment]
If there is a source of truth for those, link to it and make a ticket

**Comment by ronaldtse** [comment]
It’s already explained in the page I linked above. 

Here’s where it is shown on ITU:
https://www.itu.int/itu-t/aap/AAPRecDetails.aspx?AAPSeqNo=2035

**Comment by opoudjis** [comment]
Inserting "Draft" before doctype in coverpages where applicable.
