### ISSUE TITLE
Broken links for StandardDoc_StandardDocument page

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#173]
Reported error

> https://www.metanorma.com/specs/metanorma-model-standoc/StandardDoc_StandardDocument/

> If you click on Data Types or Bibliography, there’s a lovely 404.

**Comment by strogonoff** [comment]
The problem was that spec navigation in https://raw.githubusercontent.com/metanorma/metanorma.com/master/_specs/metanorma-model-standoc.adoc got out of sync with actual spec in https://github.com/metanorma/metanorma-model-standoc/tree/master/models.

**Comment by strogonoff** [comment]
Those menu items were not supposed to be there, since corresponding objects were removed from the spec.
