### ISSUE TITLE
Post grid layout on landing page looks broken

### ISSUE THREAD

**Issue by strogonoff** [metanorma/metanorma.com#176]
<img width="1537" alt="Screenshot 2019-11-06 at 5 57 26 PM" src="https://user-images.githubusercontent.com/292959/68288213-f60c2a00-00be-11ea-957c-c97fd6a4d80b.png">

**Comment by strogonoff** [comment]
This is a regression but I’m not certain as to which change introduced it yet

**Comment by ronaldtse** [comment]
Wow, I thought it looked fine. But I see this error now... It might be the upgrade of the Jekyll gem.

**Comment by strogonoff** [comment]
Could be. Looking at markup, something is funky with the array of blog posts created in the helpers gem, or with theme’s template logic that iterates over it. Going to release another version of Open Project theme fixing this.
