### ISSUE TITLE
Metanorma-IETF: problem with AsciiBib sample

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#191]
There is something clearly wrong with this example, the type is `googlebooks` but the link is to Amazon. The `:contributor:` attribute is empty... etc. And this reference is repeated as `ref1` and `ref2`?

Problematic line: https://github.com/metanorma/metanorma.com/pull/189#pullrequestreview-337392801

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma.com/pull/189_

**Comment by opoudjis** [comment]
> There is something clearly wrong with this example, the type is googlebooks but the link is to Amazon. 

Second link, supplied.

> The :contributor: attribute is empty... etc. 

That's necessary to start a new contributor, but not necessary for the first contributor; removed.

> And this reference is repeated as ref1 and ref2?

Fixed.

**Comment by ronaldtse** [comment]
Right now there are two “link” attributes. Is that intended? Do we support multiple links?

**Comment by opoudjis** [comment]
Yes
