### ISSUE TITLE
Providing sample documents for every standard type

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#20]
For example, for MPFA documents, we have them here:
https://github.com/riboseinc/mpfd-documents/

People usually work with only one type of standard, and that's all they need to know.  We should give them the samples they want to see, not saying something like "just read this syntax once and you can work with all types of Metanorma documents".

1. We should have a page for "General Metanorma input syntax". Right now only "AsciiDoc", but foreseeable to have LaTeX or Word.
2. Separate pages for syntaxes only pertaining to one (or more) types of standard documents.

**Comment by opoudjis** [comment]
All standards gems include in their spec/examples the same Asciidoctor document (either RFC 6350 or the ISO Rice document or both), as an example document. So the requirement for a document sample is already satisfied.

There is little syntax specific to most standards classes, except for GB and ISO. The syntactic peculiarities for each class are in the Readme of each gem, so the Asciidoctor extensions for each will need to be extracted from there. I will need to do an editorial pass to make sure they are up to date for the classes other than GB and ISO (now that the remainder of the standards all inherit from metanorma-standoc).

**Comment by strogonoff** [comment]
@opoudjis I’ll integrate the samples into project sites, so I think just the pointers would be enough. For now we can take ISO and a more generic standard type, and have up-to-date samples for those.

**Comment by opoudjis** [comment]
I have moved the Asciidoctor enhancements that are introduced in metanorma-standoc from the metanorma-iso Readme to the metanorma-standoc Readme; they are all but one of them. GB introduces one more instance, and all other variants introduce the same single instance (keyword). All documented in the readmes.

**Comment by ribose-jeffreylau** [comment]
Hi @strogonoff , the presentation that I gave is in https://github.com/CalConnect/VCARD/tree/master/presentations/20180926-calconnect-mn-authoring .  The PDF may need to be explicitly built.  Let us know if problem.  Thanks!

**Comment by ribose-jeffreylau** [comment]
@strogonoff @opoudjis 

Here is the PDF slides of the Metanorma presentation that I gave:

[20180926-calconnect-mn-authoring.pdf](https://github.com/riboseinc/metanorma.com/files/2420322/20180926-calconnect-mn-authoring.pdf)

**Comment by ronaldtse** [comment]
It's all done now.
