### ISSUE TITLE
Call different types of metanorma documents "flavors"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#21]
A "flavor" of metanorma.

We need a terms of definition document ourselves!

**Comment by opoudjis** [comment]
What am I meant to be doing here? Revise all existing /docs documents? 

I also think this is a really bad idea. It is misleading to call ISO a flavour under metanorma: it is a detailed spec with formal validation requirements, it is not merely a styling variant, as "flavour" implies.

**Comment by ronaldtse** [comment]
Well, okay, we don't want to trivialize the "variant", as it is somewhat implied with "flavor", which I do understand. But we still need a term for a "variant".

Prefer not calling it a "profile" because of its interpretation within ISO (a profile cannot be "normative").

Thoughts?

**Comment by opoudjis** [comment]
schema? layout? model? standard? (this is after all a standards spec) document type?

**Comment by ronaldtse** [comment]
"Variant" has an "adjacent" meaning instead of a "adoption" meaning.

"Layout" is for presentation.

A "the ISO metanorma standard" sounds wrong...

A "the ISO metanorma model" sounds funny too...

"Document type" is probably accurate, but we wish to have something more playful.

"variety", "class", "species"??

**Comment by strogonoff** [comment]
It seems like “ISO under Metanorma” is more than just a flavor. This is my look as more or less of an outsider.

---

In basic terms, _Metanorma-ISO_ looks like a transformer/convertor of certain valid input to specifically formatted output.

_Metanorma_ is the framework that enables quick creation of such tools—drawing an analogy with how e.g. RoR lets us quickly create webapps like Twitter.

Like any webapp would inevitably take in some sort of HTTP request, input required by Metanorma-ISO would be generally similar to input required by any other Metanorma-based tool. Such a tool takes standard markup as input and outputs standard representation; variation among output is higher since conceptually standards are similar but their presentations can be full of peculiarities.

I can see that some confusion may be introduced by the fact that Metanorma is used to denote the spec for the input (= HTTP request in our analogy), the framework that enables creation of tools that work with such input (= RoR in our analogy), and also tools created with the framework (= Twitter).

---

Based on above, my 2 cents would be that we can avoid calling Metanorma-ISO “<something> of Metanorma”, and instead call it a standard generator for ISO standards developed with Metanorma.

Metanorma in this case would be “a framework for standard generators”, which does not sound playful but may be technically correct (for which there’s its place, even if it’s not in the tagline).

**Comment by opoudjis** [comment]
The problem is that the same framework is used to generate half a dozen other standards as well, and we need a term to call that. Everything you say about the framework is true though.

**Comment by strogonoff** [comment]
It’s not a problem at all. I only named Metanorma-ISO to illustrate my point, but it applies equally to any tool be it Metanorma-ISO or Metanorma-CSD or something else.

**Comment by opoudjis** [comment]
Class, I think?

**Comment by opoudjis** [comment]
:-( Document class. Document type. Format. (And Format is not as restrictive as Layout.)

**Comment by strogonoff** [comment]
Just let it float independently ;) It’s just a processor for X standard, built with Metanorma framework. I haven’t heard any objections so far ;)

**Comment by ronaldtse** [comment]
Instance. Realization. Flavor. Branch.

**Comment by ronaldtse** [comment]
"Format" has a particular understanding as "realization of a data model in a file" i.e. XML.

**Comment by opoudjis** [comment]
@ronaldtse: I capitulate: Instance. I hate it, but I hate the other ones you proposed even more, and you hate all the ones I've suggested. :(

Is there a task on me to insert "Instance" (*shudder*) into all documentation?

**Comment by ronaldtse** [comment]
I'm not comfortable with the choice "instance"; "type" is better than that. The only issue I have with type is the similarity with "document type" within a "document type".

According to the thesaurus, "type":
> kind, sort, variety, class, category, set, genre, species, order, breed, race; style, nature, manner, rank; generation, vintage; stamp, ilk, cast, grain, mold, stripe, brand, flavor.

We can just choose one here.

**Comment by ronaldtse** [comment]
"Class" could work.

**Comment by ronaldtse** [comment]
@opoudjis "Metanorma Class" then?

**Comment by opoudjis** [comment]
Class.

I repeat the question: Is there a task on me to insert "class" into all documentation? Given how absurdly overburdened I am currently, I suggest @strogonoff do so instead...

**Comment by strogonoff** [comment]
I’ll update the docs, though “class” will sound a bit confusing to the user.

**Comment by ronaldtse** [comment]
@strogonoff how about “family”?

**Comment by opoudjis** [comment]
Metanorma family?

Metanorma standards family?

Family only makes sense as a family of documents, which implies a more informal grouping; class is more formal than that, and needs to be.

**Comment by ronaldtse** [comment]
In any case, we need to explain in detail what exactly a “class” means on our website, and provide examples of them.

**Comment by strogonoff** [comment]
Are we excluding simply “processor”?

**Comment by ronaldtse** [comment]
We really need a structural diagram and corresponding words to describe them. “Processor” should be the software that processes any text input into the Metanorma language.

**Comment by opoudjis** [comment]
This is a simple concept, and it is baffling that this ticket has been stuck for two months.

> Each standards organisation defines a presentation style and structure for the standards documents it maintains. Metanorma treats the standards documents from each standards organisation as a separate **class** of documents, to which it applies the style and structure defined by the organisation.

That's all that needs to be said.

@strogonoff I think the confusion is that there are two things being discussed here: the set of documents particular to a standard, and the realisation of the Metanorma software particular to a standard. This ticket asked for the former; hence, class of documents. 

The Metanorma software instance could be called a "processor", but that's not what this ticket has asked for. The latter has been consistently referred to in documentation as a gem, and I am not eager  to call it something else; it is certainly not a class.

**Comment by strogonoff** [comment]
@opoudjis @ronaldtse  can we call up about by the way at some convenient time (I’m on HK time currently)? There’re a couple of items on agenda, mainly about a way I think we can radically improve publicity with little to no extra effort just by coordinating content writing slightly differently.

**Comment by ronaldtse** [comment]
@strogonoff could we just write out the coordination proposal here? It makes it easier on everyone's schedule 😉

**Comment by strogonoff** [comment]
@ronaldtse I believe Nick’s style of writing is very suitable for a series of blog posts on Metanorma (which we coincidentally also want) but I’d like to get a personal feel for this first so a 15-minute call is very desirable. It’s enough if only Nick participates (we’ve never talked before), for you the schedule doesn’t have to change!

**Comment by ronaldtse** [comment]
@strogonoff got it, let's see if @opoudjis has time tomorrow.

On the other hand, Thomas wrote this in an introduction to other folks about Metanorma:

> We use metanorma (https://www.metanorma.com/) to write the document, which means it is an asciidoc (structured text) document converted into the needed output formats offering a lot of flavors (ISO, RFC, CalConnect, ...) and output formats (pdf, html, doc, xml, ...).

Somehow he called it "flavor". I'm waiting for @opoudjis 's objections 😉

**Comment by ronaldtse** [comment]
I heard it, you said it yourself 🤣

**Comment by opoudjis** [comment]
Has been done
