### ISSUE TITLE
Saving Word documents

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma.com#243]
https://github.com/metanorma/metanorma-iso/issues/340

User  @rggibb points out that, after running Metanorma, he needs to do:

> renaming the file and the usual conversion to .docx in word, by a series of save as. And then, after I'd finished all other edits, updating the ToC field after I'd finished all other edits

(In fact, you want to update all fields in Word, although I think that's the only one that matters.)

@ronaldtse replied:

> This is unavoidable under our current system, but we should improve documentation on how to deal with this. Let's do a blog post.

I ask that one of you two do it. Blog posts are in metanorma.com, in the _posts folder. Follow the pattern of the existing documents there to create a new post, and post it as a pull request.

The post should simply say:

* Metanorma generates .doc not .docx files (for rationale see https://github.com/metanorma/html2doc/wiki/Why-not-docx%3F )
* You will need to save any .doc files as .docx, if you can't deal with .doc files
* You will need to apply the required keystroke to update any fields and tables of contents. Remember to give both the Mac and the Windows keystrokes for that. https://support.office.com/en-us/article/update-fields-7339a049-cb0d-4d5a-8679-97c20c643d4e 
* If there's anything else you've found you've needed to do to Word output, add that in.

**Comment by ronaldtse** [comment]
We will need to Windows and macOS procedures separately with screenshots to help users here.

Let's use the ISO 8000-100 Ed 2 document to demonstrate how this works.

**Comment by ronaldtse** [comment]
1. Use Metanorma generate the doc.
2. Open the doc in Word. Do "Save As", change the file type to "DOCX", save.
3. Check all images and resize them if necessary.
4. Regenerate all indexes (ToC, List of tables/images if exists)
5. Save. Optionally save as PDF.

**Comment by manuel489** [comment]
Ok, I'm going to work on the Windows procedure. However, someone else would have to add the mac-OS procedure afterwards as I only possess Windows OS.

**Comment by manuel489** [comment]
Content for Windows added in https://github.com/metanorma/metanorma.com/pull/244

**Comment by manuel489** [comment]
This is done. Closing.

**Comment by manuel489** [comment]
@opoudjis , I think this is done: https://www.metanorma.com/blog/2020-04-16-saving-word-documents/. Maybe you could close this issue? (I don't have enough privileges to do so.)
