### ISSUE TITLE
Documentation: Metanorma latex math does not handle `eqnarray` environment

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#246]
```latex
\begin{eqnarray*}
         \bf{z^\prime} & = & \bf{\zeta} \\
         \bf{x^\prime} & = & \langle \bf{\eta} \times \bf{\zeta} \rangle
\end{eqnarray*}
```

Needs to be converted into this to work:
```adoc
[%unnumbered]
[latexmath]
++++
\bf{z^\prime} = \bf{\zeta}
++++
+
[%unnumbered]
[latexmath]
++++
\bf{x^\prime} = \langle \bf{\eta} \times \bf{\zeta} \rangle
++++
```

This is because `latexmlmath` does not handle alignments.

This occurred in https://github.com/metanorma/iso-10303

@manuel489 can you help document this? Thanks.

**Comment by manuel489** [comment]
Hi @ronaldtse , in those cases, I could use AsciiMath if you like. For example:

````
[%unnumbered]
[stem]
++++
{:(bb z',=,zeta),(bb x',=,<< eta xx zeta >>):}
++++
````

Which results in (.doc output): 
![equation2](https://user-images.githubusercontent.com/33627611/79754474-9eb4eb80-82e5-11ea-8f44-a223c0076833.PNG)

Let me know if you'd prefer it on this way.

**Comment by manuel489** [comment]
Ok @ronaldtse

**Comment by ronaldtse** [comment]
@manuel489 seems that a message got deleted.

```
[%unnumbered]
[stem]
++++
{:(bb z',=,zeta),(bb x',=,<< eta xx zeta >>):}
++++
```
is also fine.

The point is the user needs to know how to do this when they encounter `eqnarray`.

**Comment by manuel489** [comment]
> @manuel489 seems that a message got deleted.

Yes @ronaldtse , I deleted that message because I thought you wanted me to apply changes to the corresponding adoc files, instead of documenting the problem (i.e. I got confused :sweat:).

> The point is the user needs to know how to do this when they encounter eqnarray.

Yes, now I realize what is needed. Thanks!

**Comment by manuel489** [comment]
@ronaldtse , does this content should be published in the blog section or somewhere else?

**Comment by manuel489** [comment]
@ronaldtse this subject is added as a tip in the conversion guide (https://github.com/metanorma/editor-guide/pull/2). Will it serve on that way?

**Comment by manuel489** [comment]
PR added in https://github.com/metanorma/metanorma.com/pull/299

**Comment by manuel489** [comment]
Task is merged. Closing.
