### ISSUE TITLE
Blog: create post for yaml2text #247

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#248]
This powerful functionality must be documented in some blog post with examples!

@ribose-jeffreylau can you do it? Can copy the examples from #247.

Or better yet -- use ISO 24229 as a sample! (@w00lf did you push the changes?)

Thanks!

**Comment by w00lf** [comment]
> 24229

>Or better yet -- use ISO 24229 as a sample! (@w00lf did you push the changes?)

@ronaldtse  What change is it?

**Comment by ronaldtse** [comment]
@w00lf the change is now tracked here: https://gitlab.com/calconnect/tc-localization/csd-transcription-systems/-/merge_requests/28

**Comment by ribose-jeffreylau** [comment]
Fixed by https://github.com/metanorma/metanorma.com/commit/51a9ae0d0a77d0e33ef2a8d02fbe0fcea952334e
