### ISSUE TITLE
Add FAQ entry: (C) copyright symbol

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#253]
> Both (C) and (c) are producing copyright symbol in Metanorma. In AsciiDoctor, I was able to find that only (C) produces this symbol.

> When writing \(C) in .adoc, expected result is produced, i.e. (C). However, backslash is generated in DOC/PDF in case of writing \(c) in .adoc and I wasn't able to find the proper way to generate (c) instead of the copyright symbol.

The difference betweeen Asciisdoctor and Metanorma is because I repair these expansions using the gem sterile (for smart quotes), and sterile also has a more liberal set of symbols. 

My generic advice to @manuel489 from yesterday, https://github.com/metanorma/metanorma-standoc/issues/263, also applies here. If you want to prevent a combination of two or more characters from being converted to a single symbol, don't use backslash, which is completely at the mercy of what Asciidoctor has implemented. Instead, interrupt the sequence using the Zero Width Non Join character, U+200C. It is invisible, but it prevents combinations of characters from being recognised as such. So in this case:

`(&#x200c;c)`

_Originally posted by @opoudjis in https://github.com/metanorma/metanorma-nist/issues/197#issuecomment-622185712_

**Comment by opoudjis** [comment]
Um, guys, I've already done this. https://github.com/metanorma/metanorma.com/pull/252, https://www.metanorma.com/author/ref/asciidoc-tips/#asciidoc_escaping

@ronaldtse, we've been through this several times: I always document new features as I go.
