### ISSUE TITLE
Missing `mailto:` in the example

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma.com#270]
I noticed that `mailto:` isn't written in the following example before the email in https://www.metanorma.com/author/topics/document-format/text/: 

[align=left]
Vache Equipment +
Fictitious +
World +
gehf@vacheequipment.fic

I believe it would be good to change `gehf@vacheequipment.fic` to `mailto:gehf@vacheequipment.fic`, in order to follow the general rule for writing emails. Since I don't have writing permissions in metanorma.com, I am opening a ticket for this.

**Comment by opoudjis** [comment]
Thank you @anermina!
