### ISSUE TITLE
Write blog post about `metanorma setup` and Fontist

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#272]
Inheriting some information from #271 , let's have a blog post that describes the thinking of `metanorma setup` and how it is used, where the fonts are setup, etc.

**Comment by ronaldtse** [comment]
This task is still relevant. We need to document how to use Metanorma with Fontist to install fonts (using a local executable Metanorma, or Metanorma docker which requires setting up fonts on a new volume).

**Comment by CAMOBAP** [comment]
Because we removed metanorma setup command, it's nor relevant anymore, thanks for note
