### ISSUE TITLE
Document the Word doc generation caveats

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#28]
The Word doc format produced by Metanorma is called Word MHT, which is not a typical Word file.

Caveats:

1. The Table of Contents must be updated using real Microsoft Word to have correct page numbers
2. The Metanorma generated Word document cannot be read by OpenOffice / LibreOffice.

In order to convert the `.doc` file into a typical Word file (.doc or .docx), you need to follow these steps: 
https://github.com/riboseinc/html2doc#converting-document-output-to-native-word-docx

This information should be put on metanorma.com.

**Comment by opoudjis** [comment]
There's information in https://github.com/riboseinc/metanorma-iso/blob/master/docs/outputs.adoc that presumably needs to go to metanorma.com as well.

**Comment by opoudjis** [comment]
Has been addressed: https://www.metanorma.com/author/topics/building/output-formats/
