### ISSUE TITLE
Fix quote example image with stray comma?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#289]
Problematic image:
<img width="821" alt="image" src="https://user-images.githubusercontent.com/11865/83756109-25106b80-a6a1-11ea-8b44-3e5052df4a60.png">

There is a stray comma in the quote attribution?

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma.com/pull/286#issuecomment-638813903_

**Comment by opoudjis** [comment]
Yeah, there's a problem: what I've documented is not what I've implemented.

Debugging, and will supply right rendering.

**Comment by opoudjis** [comment]
Tell a lie: the implementation was correct, the example was utterly incorrect. Fixing.

**Comment by opoudjis** [comment]
Manuel, can I instead get you to fix this? Sorry:

Example should be:

````
[source,asciidoc]
--

[quote, ISO, "ISO_9735,section=1,EDIFACT"]
_____
This International Standard gives the minimum specifications for rice (_Oryza sativa_ L.)
which is subject to international trade. It is applicable to the following types: husked rice
and milled rice, parboiled or not, intended for direct human consumption. It is neither
applicable to other products derived from rice, nor to waxy rice (glutinous rice).
_____

....

[bibliography]
== Bibliography
* [[[ISO_9735,ISO 9735 (all parts)]]], _Electronic data interchange for administration commerce and transport (EDIFACT) -- Application level syntax rules_.
````

Note that the quote source is formatted just like a bibliographic citation, and is processed in the same way: it can consist, as is done here, of a bibliographic anchor (ISO_9735), a set of localities (section=1), and an optional text to display instead of the regular citation.

**Comment by manuel489** [comment]
> Manuel, can I instead get you to fix this? Sorry:

Sure @opoudjis
