### ISSUE TITLE
Update general bibliography guidance to make exception to IETF, provide guidance for IETF

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#296]
The "normal" bibliography guidance differs from IETF, where the Normative References and Informative References are two separate sections, and that the Informative References section is optional.

We should update metanorma.com for that. Thanks!

Ping @manuel489

_Originally posted by @ronaldtse in https://github.com/metanorma/mn-templates-ietf/pull/12#issuecomment-643041672_

**Comment by manuel489** [comment]
PR added in https://github.com/metanorma/metanorma.com/pull/300

**Comment by manuel489** [comment]
Task is merged. Closing.
