### ISSUE TITLE
Provide guidance on T&D `[.nonterm]` and anchor format requirements

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#313]
Explain the following in the website:

2. In the T&D clause, if a subclause contains terms underneath, DO NOT USE `[.nonterm]` -- otherwise Metanorma will skip all terms in that subclause. `[.nonterm]` only applies to "leaf nodes", it is equivalent to telling Metanorma to stop processing that subclause completely.

3. Anchors, references and bib refs: they cannot contain colons -- because they are written to XML. XML does not support colon, spaces, and phrases that start with numbers in `id`.

_Originally posted by @ronaldtse in https://github.com/metanorma/iso-10303/pull/71#issuecomment-661983357_

**Comment by manuel489** [comment]
> Anchors, references and bib refs: they cannot contain colons -- because they are written to XML. XML does not support colon, spaces, and phrases that start with numbers in id.

@ronaldtse, regarding cross-references, the [documentation](https://www.metanorma.com/author/topics/document-format/text/#cross-references) states the following:

*"The anchor ID must follow the NCName constraints of `xml:id`: 
 it must start with a letter, an underscore, or a colon."*

So, I think there is a contradiction here. Or maybe the colon is not permitted in between?

**Comment by ronaldtse** [comment]
Thanks, the documentation is indeed wrong. NCName does not allow the colon. It is explained here: https://stackoverflow.com/questions/6811188/why-does-jing-not-allow-a-colon-in-an-id-attribute

**Comment by manuel489** [comment]
Thanks @ronaldtse !
PR added in https://github.com/metanorma/metanorma.com/pull/314

**Comment by ronaldtse** [comment]
Thanks @manuel489 !
