### ISSUE TITLE
Outdated copyright year!

### ISSUE THREAD

**Issue by abunashir** [metanorma/metanorma.com#355]
Hallo there, I just came across this one today, the website is using 2018 as copyright year in the footer, so I thought I would report it here. Ideally, I think it might be a good idea to change it to be dynamic so we don't have to update that every year but I would leave that up to you guys :)

<img width="689" alt="Screen Shot 2020-11-03 at 6 12 33 PM" src="https://user-images.githubusercontent.com/1220911/98018216-92ffc100-1e00-11eb-977f-f939f2ea6428.png">

cc: @strogonoff, @ronaldtse

**Comment by strogonoff** [comment]
Thanks Abu!
