### ISSUE TITLE
Add the `metanorma.yml` default config path to documentation+blog post

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#377]
@abunashir Could you help add the `metanorma.yml` default config path to documentation+blog post?

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-cli/issues/199#issuecomment-751419495_

**Comment by ronaldtse** [comment]
This is related to #375

**Comment by abunashir** [comment]
I've added these details to the attached commit, thanks!
