### ISSUE TITLE
Document an isolated hyphen is rendered as em-dash in Metanorma

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma.com#395]
*In relation to https://github.com/metanorma/mn2pdf/issues/57*

Isolated hyphen (` - `), is rendered as em-dash. 

For example, `188 - 200`:

![Capture1](https://user-images.githubusercontent.com/33627611/105782324-b0997e00-5f4a-11eb-85ca-a3b035567840.PNG)

This is a reminder to document this normalization.

Thanks!

**Comment by manuel489** [comment]
Btw, I tested `188 -- 200` expecting to get an n-dash but got m-dash as well.

**Comment by strogonoff** [comment]
@manuel489 yes, I think this comes from Jekyll’s processing (https://stackoverflow.com/questions/16871088/how-to-escape-double-dash-in-markdown).

Em dash is used pretty often in English typography so presumably that’s why Jekyll does this, although *with ranges in particular* I think it’s more appropriate to use the en dash.

As a workaround, I believe you can enter en (or em) dashes directly when authoring the source. There are shortcuts for that on macOS (hold option or option-shift with dash), and I presume other OS have something similar as well.

**Comment by ronaldtse** [comment]
Probably need to use nbsp for the isolated hyphen, Jekyll is probably not meant to reproduce exact typography that is necessary in such documentation. We just have to work around it.

**Comment by manuel489** [comment]
Hi @strogonoff,
I'm actually referring to Metanorma processing. This has nothing to do with Jekyll. It's just that Nick asked me to remind him to document about a normalization rule implemented in Metanorma. Maybe I shouldn't have posted this ticket here?

**Comment by ronaldtse** [comment]
Oh, then let's rename the issue to state that.

**Comment by ronaldtse** [comment]
> Btw, I tested `188 -- 200` expecting to get an n-dash but got m-dash as well.

And if this is a bug, please report at metanorma/metanorma-standoc. Thanks!

**Comment by manuel489** [comment]
Thanks @ronaldtse. yeah I was going to report in metanorma-standoc. But as I don't have privileges to set assignees there (and I understand why), I decided to put it here. Ok.

**Comment by opoudjis** [comment]
I'm going to document the existing behaviour in metanorma, which uses " - " for em dash and "--" for en-dash. Also going to refactor the https://www.metanorma.com/author/topics/document-format/text/ page, it has become much too big.

**Comment by opoudjis** [comment]
Ah, I see what's happened.

Right now `--` is being treated like ` - `, as an em-dash, *with the exception* of dates coming from relaton, where they are treated as en-dash.

I'm realising that that is quite confusing. The normalisation of "--" and "-" needs to happen in Relaton, treating dashes in dates and titles differentially. In Metanorma itself, we should do one of the following:

* " -- " is always en-dash: `9 -- 12; the New York -- London train; this - is prophetic` (That reflects TeX usage for en-dash; TeX uses "---" always for em-dash.)
* "--" is en-dash (no space between words), " -- " is em-dash: `9--12; the New York--London train; this -- is prophetic`

I would favour the latter. If we change this, Relaton also needs to manipulate the dashes in ISO, preferably so they arrive in Metanorma as true em-dashes and en-dashes. (-- in date = en-dash, -- elsewhere is em-dash).

**Comment by ronaldtse** [comment]
Agree with @opoudjis

**Comment by manuel489** [comment]
In my opinion, as an editor, I vote on using asciidoc convention; `--` is always an m-dash.
I'd rather to use an entity (like `&#8211;`) or an alt code in the keyboard to place an n-dash when it's required.
@anermina what do you think about this?

**Comment by anermina** [comment]
In my opinion, second proposed option would be the best choice.

> "--" is en-dash (no space between words), " -- " is em-dash

**Comment by manuel489** [comment]
> In my opinion, second proposed option would be the best choice.
> 
> > "--" is en-dash (no space between words), " -- " is em-dash

I don't have problem with this neither. 
However, I'd recommend to introduce an escape 
option for cases where an m-dash between 
words with no white spaces is required (it's not that common, but I've seen it).

**Comment by strogonoff** [comment]
Sorry to chime in, but wouldn’t it be reasonable to just allow the user to enter typography as unicode characters directly? Em dash like —, en dash like –, there are shortcuts in OS.

**Comment by manuel489** [comment]
> Sorry to chime in, but wouldn’t it be reasonable to just allow the user to enter typography as unicode characters directly? Em dash like —, en dash like –, there are shortcuts in OS.

It is allowed already. My recommendation was just for practical purposes.

**Comment by opoudjis** [comment]
Need to get @andrew2net to action this in ISO. Will write ticket shortly.

**Comment by opoudjis** [comment]
OK, am not proposing a keyboard shortcut for en-dash at this time, will document that in metanorma.com.
