### ISSUE TITLE
Add favicon 

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#41]

**Comment by strogonoff** [comment]
https://github.com/riboseinc/jekyll-theme-open-project/issues/37

**Comment by strogonoff** [comment]
Favicons were added. (For the time being, symbol rendering is a bit wanting—lighthouse has too much fine detail in 32x32, similar problem to Ribose Open symbol; ideally a separate lighthouse would be designed for small sizes like this.)

**Comment by strogonoff** [comment]
https://github.com/metanorma/metanorma.com/commit/81a1e42df5ae24656eb664c8abcee91fc15055ef
