### ISSUE TITLE
Migrate this repository to github.com/metanorma

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma.com#69]
The repository github.com/metanorma has been set up to host all Metanorma related work. This is one such piece of work. While the migration will be slow (there is a lot to do, and a lot of interdependencies), we need to schedule migration for all related repositories.

Migration to Metanorma:

* Repost the repository to http://github.com/metanorma/X
  * This should be as simple as changing the following field in .git/config: `[remote "origin"]   url = https://github.com/riboseinc/metanorma-iso.git`. Refer https://help.github.com/en/articles/transferring-a-repository
* If this is a Ruby gem, change the address of the repository in the *.gemspec
* Delete all files but the Readme in the riboseinc repository
* Replace the Readme in the riboseinc repository with the message "Repository migrated to http://github.com/metanorma/X
* Update the links to the repository in any documentation you maintain
* Link the README in the new location to updated links for appveyor, CodeClimate, travis, etc. New links to travis should be to travis-ci.com, not travis-ci.org.
* Notify @opoudjis and @strogonoff when you have migrated the repository. They will then update the links to the repository in any documentation they maintain.

**Comment by ronaldtse** [comment]
@strogonoff this is for you. Can you accept the org invitation for the assignment? Thanks!

**Comment by opoudjis** [comment]
There is probably very little for you to do now: just ensure that links point to http://github.com/metanorma instead of http://github.com/riboseinc (I already have started doing so in my edits, and will keep doing so.)
